### ISSUE TITLE
Pakeisti reliatyvias nuorodas

### ISSUE THREAD

**Issue by sirex** [python-dirbtuves/akl.lt#23]
Importuojant duomenis reikia pakeisti reliatyvias nuorodas į wagtail nuorodas.

Pavyzdžiui http://127.0.0.1:8000/ak/dokumentacija/ puslapyje yra daug `?doc=jabber.html` ir panašių nuorodų. Jov siso turėtų būti pakeistos į `/ak/dokumentacija/jabber/` arba panaudoti Wagtail URL žymes, kažkur mačiau, kad kažkas tokio yra.

**Comment by strazdas** [comment]
Ar atlikus #15 vis dar reikia įgyvendinti šį reikalavimą. Juk senos nuorodos bus ir taip nukreipiamos į teisingus puslapius.

**Comment by sirex** [comment]
Šiaip jau reikėtų. Kadangi #15 užduotyje padarytas peradresavimas skirtas išorinėms nuorodoms, o vidines derėtų susitvarkyti.

Bet, iš esmės ši užduotis nėra prioritetinė.

**Comment by sirex** [comment]
Peržiūrėjęs importuotus duomenis pastebėjau, kad daugelis nuorodų yra reliatyvios, t.y. klijuojasi ant esamo kelio ir todėl neveikia. Taip pat dalis nuorodų yra su domeno vardu. Papildomai, jei nuorodos nebus konvertuotos, jų nebus galima redaguoti administravimo aplinkoje.

Todėl nuorodas konvertuoti tikrai reikia.
