### ISSUE TITLE
Išjungti programų katalogą

### ISSUE THREAD

**Issue by sirex** [python-dirbtuves/akl.lt#29]

**Comment by sirex** [comment]
Programų puslapio objektas buvo sukurtas rankomis, todėl nieko daryti nereikėjo.

**Comment by chompomonim** [comment]
O kodėl išjungti? Nutarėt išvis atsisakyti tokio katalogo?

**Comment by sirex** [comment]
Nutarėm išjungti beta paleidimui, kadangi prie jo reikia daugiau laiko. Programų katalogą darysim vėliau.
