### ISSUE TITLE
RSS naujienoms

### ISSUE THREAD

**Issue by sirex** [python-dirbtuves/akl.lt#31]
Padaryti naujienų RSS.

**Comment by strazdas** [comment]
Spėju naudosime [PyRSS2Gen](https://pypi.python.org/pypi/PyRSS2Gen/1.1), nes [tai populiariausias RSS generuojanti biblioteka](http://pypi-ranking.info/search/rss/)?

**Comment by sirex** [comment]
@strazdas Django has it build-int: https://docs.djangoproject.com/en/1.8/ref/contrib/syndication/ so I would suggest to use buildout RSS generator, unless PyRSS2Gen has some significant advantages over Django RSS generator?

@strazdas for the communication language, see: https://groups.google.com/d/msg/python-dirbtuves/g26EN1DAIac/TsIbyM_wqs8J

**Comment by sirex** [comment]
We'v all worked hard, the plan executed as expected.
