### ISSUE TITLE
Galimybė pasiūlyti AKL naujieną

### ISSUE THREAD

**Issue by sirex** [python-dirbtuves/akl.lt#32]
Iš naujienų puslapio paspaudus nuorodą „Pasiūlyk naujieną!“, turi atsidaryti naujienos forma. Pasiūlyta naujiena turi būti įtraukta į laukiančių peržiūros naujienų sąrašą ir visiems naujienų moderatoriams turi būti išsiųstas el. laiškas su informacija, kad yra naujienų laukiančių patvirtinimo.

Naujienas gali siūlyti tik registruoti naudotojai.

**Comment by strazdas** [comment]
Realizuota galimybė naujienas siūlyti tiek registruotiems, tiek anoniminiams naudotojams.
