### ISSUE TITLE
Sutvarkyti paveiksliukų pozicionavimo stilius

### ISSUE THREAD

**Issue by sirex** [python-dirbtuves/akl.lt#44]
Wagtail paveiksliukai turi `lphoto` ir `rphoto` CSS klases, kurios šiuo metu neturi jokio stiliaus. Reikėtų aprašyti stilius, kad paveiksliukai būtų pozicionuojami teisingai.

Pavyzdys, kur tai pasireiškia: http://127.0.0.1:8000/apie/apie/

**Comment by strazdas** [comment]
ae0e42f closes the issue
