### ISSUE TITLE
Upgrade Django to 1.8

### ISSUE THREAD

**Issue by sirex** [python-dirbtuves/akl.lt#46]
Django 1.8 jau išleistas, reikėtų atnaujinti ir akl.lt projektą.

https://www.djangoproject.com/weblog/2015/apr/01/release-18-final/

**Comment by frgtn** [comment]
:+1:

**Comment by sirex** [comment]
Wagtail does not support django 1.8 yet. It will be supported from wagtail version 1

**Comment by strazdas** [comment]
b0ed834
